### ISSUE TITLE
Пример node.js voice kit не работает

### ISSUE THREAD

**Issue by stormBMO** [TinkoffCreditSystems/tinkoff-speech-api-examples#49]
После установок пакетов и выполнения любой команды из примеров выдает ошибок:
```
C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:411
        throw Error("no such Type or Enum '" + path + "' in " + this);
        ^

Error: no such Type or Enum 'google.rpc.Status' in Type .tinkoff.cloud.longrunning.v1.Operation
    at Type.lookupTypeOrEnum (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:411:15)
    at Field.resolve (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\field.js:268:94)
    at Type.set (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\type.js:177:38)
    at Type.get (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\type.js:155:45)
    at Field.resolve (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\field.js:317:21)
    at Type.resolveAll (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\type.js:304:21)
    at Namespace.resolveAll (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:308:25)
    at Namespace.resolveAll (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:308:25)
    at Namespace.resolveAll (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:308:25)
    at Namespace.resolveAll (C:\Projects\voicekit-examples\nodejs\node_modules\protobufjs\src\namespace.js:308:25)
```
Пробовал запускать на MacOS 11.5.2 (Node.js 15.8.0) и Windows 10 (Node.js 16.4.2)

**Comment by igords** [comment]
Просто закомментируйте строку `google.rpc.Status error = 5;` в apis/tinkoff/cloud/longrunning/v1/longrunning.proto

**Comment by mykola-semenov** [comment]
Добрый вечер! А вы клонируете [сабмодули](https://github.com/TinkoffCreditSystems/voicekit-examples/tree/master/third_party)? Просто необходимые типы определяются в сабмодуле googleapis, поэтому репозиторий необходимо клонировать рекурсивно.

**Comment by valery-lyapustin** [comment]
> 

Спасибо!
